# 어플리케이션 모드 설정
spring:
  main:
    web-application-type: none

# 톰캣 서버 설정
server:
  port: 8888
  servlet:
    encoding:
      force: true

# 데이터 소스
board:
  jdbc:
    driverClass: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 


# 로그 레벨 변경
logging:
  level:
    '[org.springframework]': info